pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                node('Node JS 20') {
                    sh 'npm install'
                }
            }
        }
        stage("Run App") {
            steps {
                node('Node JS 20') {
                    sh 'node app.js'
                }
            }
        }
    }
}
