pipeline {
    agent any
    stages{
        stage("Build & Test") {
            steps{
                sh "npm install"
            }
        }
        stage("Run App") {
            steps{
                sh "node app.js"
            }
        }
    }
}
